name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.12

    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -i smoke tests

    - name: Debug PR origin
      if: github.event_name == 'pull_request'
      run: |
        echo "PR source repo: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "Target repo: ${{ github.repository }}"

    - name: Run Robot Reporter only if not fork
      run: |
        echo "Checking if PR is from fork..."
        if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
          echo "Skipping Robot Reporter (PR from fork)"
          exit 0
        fi

        echo "Running Robot Reporter via Docker"
        docker run --rm \
          -e GH_ACCESS_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
          -e REPOSITORY="${{ github.event.repository.name }}" \
          -e REPOSITORY_OWNER="${{ github.repository_owner }}" \
          -e COMMIT_SHA="${{ github.sha }}" \
          -e REPORT_PATH="/logs" \
          -e SUMMARY=true \
          -e ONLY_SUMMARY=false \
          -e SHOW_PASSED_TESTS=true \
          -v "${{ github.workspace }}/logs:/logs" \
          joonvena/robot-reporter:v2.4

    - name: Upload Robot Logs
      uses: actions/upload-artifact@v4
      with:
        name: robot-logs
        path: logs

