name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.12

    - name: Install Deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -i smoke tests

    - name: Debug PR origin
      if: github.event_name == 'pull_request'
      run: |
        echo "PR source repo: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "Target repo: ${{ github.repository }}"

    - name: Robot Reporter
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload Robot Logs
      uses: actions/upload-artifact@v4
      with:
        name: robot-logs
        path: logs
